# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74911c7083e3d5e8d9a1e167466470387b5a00087c2b5465b0617fd8101ee383527ebb85d411385a9741d87015e305fba9edc68a41aaa372566c9fea1059e2be

test:
  secret_key_base: def4582e9863bd53091db75c26e128509948ef77cfc4a3d88aeb7bcd1bc6adb44b0385e71c69f403b84bd3a568e1898c6d3c393441007663d97e86b6ae694000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
